import type { CombatRole } from '../lib/content/types';

export interface MonsterJudgment {
  combat_role: CombatRole;
  race?: string;
}

// Judgment-based facet data for every monster in scripts/seed-nimble-monsters.ts
// (nimble) and the D&D SRD monster set (srd). The two systems are namespaced
// separately because 17 monster names exist in both sources (Bandit, Bandit
// Captain, Basilisk, Black Pudding, Bugbear, Bulette, Cloaker, Cultist, Druid,
// Ettercap, Ghoul, Giant Spider, Glabrezu, Gnoll, Goblin, Gray Ooze, Griffon) --
// a single flat name-keyed map would either collide (TS1117 duplicate object-
// literal keys) or cause a downstream script to silently update the wrong
// system's row for one of these shared names.
// combat_role is judged from each monster's primary/first-listed named action.
// race is only populated for Nimble monsters whose `tags` entry is a thematic
// grouping (Kobolds, Goblins, Bandits, Snakemen, Dungeon Denizens, Hill & Field,
// Forest Denizens, Underground, Cultists/Horrors, Legendary) rather than an
// actual creature type already present in tags (Fey, Fiend, Undead, Dragon,
// Giant Bug), which a separate deterministic function already handles. SRD
// race is handled elsewhere and is intentionally omitted here.
export const JUDGMENT_MONSTER_DATA: {
  nimble: Record<string, MonsterJudgment>;
  srd: Record<string, MonsterJudgment>;
} = {
  nimble: {
    // ============================= FEY =============================
    Sprite: { combat_role: 'Ranged' },
    Faerie: { combat_role: 'Ranged' },
    'Faerie Troubadour': { combat_role: 'Ranged' },
    'Faerie Merrymaker': { combat_role: 'Ranged' },
    'Faerie Trickmage': { combat_role: 'Ranged' },
    Gremlin: { combat_role: 'Melee' },
    'Gremlin Wrestler': { combat_role: 'Melee' },
    'Gremlin Roastmaster': { combat_role: 'Melee' },
    Bogey: { combat_role: 'Melee' },
    'Mav, The Winter Queen': { combat_role: 'Ranged' },
    'Razzle, Gremlin Iconoclast': { combat_role: 'Melee' },

    // ============================= FIENDS =============================
    Nalfeshnee: { combat_role: 'Ranged' },
    Glabrezu: { combat_role: 'Melee' },
    Hezrou: { combat_role: 'Melee' },
    Vrock: { combat_role: 'Ranged' },
    'Incubus/Succubus': { combat_role: 'Ranged' },
    Hookspawn: { combat_role: 'Melee' },
    'Spiny Fiend': { combat_role: 'Melee' },
    Imp: { combat_role: 'Melee' },
    Stenchling: { combat_role: 'Melee' },
    Executor: { combat_role: 'Ranged' },
    Lashfiend: { combat_role: 'Ranged' },
    Justiciar: { combat_role: 'Ranged' },
    Overlord: { combat_role: 'Ranged' },
    Hierarch: { combat_role: 'Ranged' },
    Pactmonger: { combat_role: 'Ranged' },
    Grumbulus: { combat_role: 'Melee' },
    Quasit: { combat_role: 'Melee' },
    Lumbrax: { combat_role: 'Melee' },
    'Vorgrath, the Insatiable': { combat_role: 'Ranged' },

    // ============================= GIANT BUGS =============================
    'Bug Minion': { combat_role: 'Melee' },
    'Giant Bug': { combat_role: 'Melee' },
    'Toughrider Bug': { combat_role: 'Melee' },
    'Jacker Bug': { combat_role: 'Melee' },
    'Acidshot Bug': { combat_role: 'Ranged' },
    'Bonfire Bug': { combat_role: 'Melee' },
    'Hivedriver Bug': { combat_role: 'Melee' },
    'Vicejaw Bug': { combat_role: 'Melee' },
    'Thrum Bug': { combat_role: 'Ranged' },
    Spitbug: { combat_role: 'Ranged' },
    'Maneater Bug': { combat_role: 'Melee' },
    'Rhino Bug': { combat_role: 'Melee' },
    'Ballistic Bug': { combat_role: 'Ranged' },
    'Broodfly Drake': { combat_role: 'Ranged' },

    // ============================= GMG: KOBOLDS =============================
    'Kobold Minion': { combat_role: 'Melee', race: 'Humanoid' },
    Kobold: { combat_role: 'Melee', race: 'Humanoid' },
    'Kobold Sneak': { combat_role: 'Melee', race: 'Humanoid' },
    'Kobold Clanger': { combat_role: 'Melee', race: 'Humanoid' },
    'Kobold Trapper': { combat_role: 'Ranged', race: 'Humanoid' },
    'Kobold Denwarden': { combat_role: 'Melee', race: 'Humanoid' },

    // ============================= GMG: GOBLINS =============================
    'Goblin Minion': { combat_role: 'Melee', race: 'Humanoid' },
    Goblin: { combat_role: 'Melee', race: 'Humanoid' },
    Bugbear: { combat_role: 'Melee', race: 'Humanoid' },
    'Goblin Taskmaster': { combat_role: 'Melee', race: 'Humanoid' },
    'Goblin Ratrider': { combat_role: 'Melee', race: 'Humanoid' },

    // ============================= GMG: BANDITS =============================
    'Bandit Minion': { combat_role: 'Melee', race: 'Humanoid' },
    Bandit: { combat_role: 'Melee', race: 'Humanoid' },
    'Bandit Bruiser': { combat_role: 'Melee', race: 'Humanoid' },
    'Bandit Hunter': { combat_role: 'Ranged', race: 'Humanoid' },
    'Bandit Assassin': { combat_role: 'Melee', race: 'Humanoid' },
    'Bandit Mage': { combat_role: 'Ranged', race: 'Humanoid' },
    'Bandit Captain': { combat_role: 'Melee', race: 'Humanoid' },

    // ============================= GMG: SNAKEMEN =============================
    'Snakeman Minion': { combat_role: 'Melee', race: 'Humanoid' },
    Snakeman: { combat_role: 'Melee', race: 'Humanoid' },
    'Cobra Captain': { combat_role: 'Melee', race: 'Humanoid' },
    'Giant Cobra': { combat_role: 'Melee', race: 'Humanoid' },

    // ============================= GMG: DUNGEON DENIZENS =============================
    Stirge: { combat_role: 'Melee', race: 'Beast' },
    'Greater Stirge': { combat_role: 'Melee', race: 'Beast' },
    'Tiny Mimic': { combat_role: 'Melee', race: 'Monstrosity' },
    'Small Mimic': { combat_role: 'Melee', race: 'Monstrosity' },
    'Medium Mimic': { combat_role: 'Melee', race: 'Monstrosity' },
    'Gray Ooze': { combat_role: 'Melee', race: 'Ooze' },
    'Ochre Jelly': { combat_role: 'Melee', race: 'Ooze' },
    'Black Pudding': { combat_role: 'Melee', race: 'Ooze' },
    'Elder Ooze': { combat_role: 'Ranged', race: 'Ooze' },

    // ============================= GMG: HILL & FIELD =============================
    Gnoll: { combat_role: 'Melee', race: 'Humanoid' },
    'Gnoll Packleader': { combat_role: 'Melee', race: 'Humanoid' },
    Worg: { combat_role: 'Melee', race: 'Beast' },
    'Hill Giant': { combat_role: 'Melee', race: 'Giant' },
    Bulette: { combat_role: 'Melee', race: 'Monstrosity' },
    Troll: { combat_role: 'Melee', race: 'Giant' },
    'Blue Drake': { combat_role: 'Melee' },
    Griffon: { combat_role: 'Melee', race: 'Monstrosity' },
    Roc: { combat_role: 'Ranged', race: 'Monstrosity' },

    // ============================= GMG: UNDEAD =============================
    Skeleton: { combat_role: 'Ranged' },
    Zombie: { combat_role: 'Melee' },
    Ghoul: { combat_role: 'Melee' },
    Specter: { combat_role: 'Melee' },
    'Ogre Zombie': { combat_role: 'Melee' },
    Mummy: { combat_role: 'Melee' },
    'Giant Zombie': { combat_role: 'Melee' },
    Wraith: { combat_role: 'Ranged' },
    'Mummy Lord': { combat_role: 'Melee' },

    // ============================= GMG: FOREST DENIZENS =============================
    Duskprowler: { combat_role: 'Melee', race: 'Beast' },
    Basilisk: { combat_role: 'Ranged', race: 'Monstrosity' },
    Druid: { combat_role: 'Ranged', race: 'Humanoid' },
    Seedling: { combat_role: 'Ranged', race: 'Plant' },
    Acidpod: { combat_role: 'Melee', race: 'Plant' },
    Tangler: { combat_role: 'Ranged', race: 'Plant' },
    Rootbreaker: { combat_role: 'Melee', race: 'Plant' },
    Treant: { combat_role: 'Ranged', race: 'Plant' },

    // ============================= GMG: CULTISTS/HORRORS =============================
    Cultist: { combat_role: 'Melee', race: 'Humanoid' },
    Fanatic: { combat_role: 'Melee', race: 'Humanoid' },
    Doomsayer: { combat_role: 'Ranged', race: 'Humanoid' },

    // ============================= GMG: UNDERGROUND =============================
    'Giant Spider': { combat_role: 'Ranged', race: 'Giant Bug' },
    Ettercap: { combat_role: 'Melee', race: 'Monstrosity' },
    Nestweaver: { combat_role: 'Ranged', race: 'Giant Bug' },
    Cloaker: { combat_role: 'Melee', race: 'Monstrosity' },
    'Umber Hulk': { combat_role: 'Melee', race: 'Monstrosity' },
    'Great Worm': { combat_role: 'Ranged', race: 'Monstrosity' },

    // ============================= GMG: LEGENDARY MONSTERS =============================
    'Pudge the Blunderer': { combat_role: 'Melee', race: 'Giant' },
    'Kelebek & Poppy': { combat_role: 'Melee', race: 'Humanoid' },
    'Grimbeak, the Unyielding': { combat_role: 'Ranged', race: 'Monstrosity' },
    'Thorn Quickblade': { combat_role: 'Ranged', race: 'Humanoid' },
    'Ravager of the Lowlands': { combat_role: 'Ranged', race: 'Monstrosity' },
    'Nalzar, Apex Predator': { combat_role: 'Melee' },
    'Queen Aranya, Broodmother': { combat_role: 'Melee', race: 'Giant Bug' },
    'Florindris, Bane of the Forest': { combat_role: 'Ranged' },
    'General Flameheart': { combat_role: 'Ranged', race: 'Giant' },
    'Vael, Undying Necromancer': { combat_role: 'Ranged' },
    'Titan of the Deep Woods': { combat_role: 'Ranged' },
    "Ul'vek, Psionic Despot": { combat_role: 'Ranged', race: 'Aberration' },
    'Dravok, All-Seeing Tyrant': { combat_role: 'Ranged', race: 'Aberration' },
    'Azriel, Lord of Pain & Flame': { combat_role: 'Ranged' },
    'Gloomwing the Cruel': { combat_role: 'Ranged' },
    'Alaric Draegoth, the Crimson Count': { combat_role: 'Melee' },
    'Caerys, the Hollow Star': { combat_role: 'Melee', race: 'Aberration' },
  },

  srd: {
    // ============================= D&D SRD MONSTERS (A–Hawk, batch B1) =============================
    'Aboleth': { combat_role: 'Ranged' },
    'Acolyte': { combat_role: 'Ranged' },
    'Adult Black Dragon': { combat_role: 'Ranged' },
    'Adult Blue Dragon': { combat_role: 'Ranged' },
    'Adult Brass Dragon': { combat_role: 'Ranged' },
    'Adult Bronze Dragon': { combat_role: 'Ranged' },
    'Adult Copper Dragon': { combat_role: 'Ranged' },
    'Adult Gold Dragon': { combat_role: 'Ranged' },
    'Adult Green Dragon': { combat_role: 'Ranged' },
    'Adult Red Dragon': { combat_role: 'Ranged' },
    'Adult Silver Dragon': { combat_role: 'Ranged' },
    'Adult White Dragon': { combat_role: 'Ranged' },
    'Air Elemental': { combat_role: 'Melee' },
    'Ancient Black Dragon': { combat_role: 'Ranged' },
    'Ancient Blue Dragon': { combat_role: 'Ranged' },
    'Ancient Brass Dragon': { combat_role: 'Ranged' },
    'Ancient Bronze Dragon': { combat_role: 'Ranged' },
    'Ancient Copper Dragon': { combat_role: 'Ranged' },
    'Ancient Gold Dragon': { combat_role: 'Ranged' },
    'Ancient Green Dragon': { combat_role: 'Ranged' },
    'Ancient Red Dragon': { combat_role: 'Ranged' },
    'Ancient Silver Dragon': { combat_role: 'Ranged' },
    'Ancient White Dragon': { combat_role: 'Ranged' },
    'Androsphinx': { combat_role: 'Melee' },
    'Animated Armor': { combat_role: 'Melee' },
    'Ankheg': { combat_role: 'Ranged' },
    'Ape': { combat_role: 'Melee' },
    'Archmage': { combat_role: 'Ranged' },
    'Assassin': { combat_role: 'Ranged' },
    'Awakened Shrub': { combat_role: 'Melee' },
    'Awakened Tree': { combat_role: 'Melee' },
    'Axe Beak': { combat_role: 'Melee' },
    'Azer': { combat_role: 'Melee' },
    'Baboon': { combat_role: 'Melee' },
    'Badger': { combat_role: 'Melee' },
    'Balor': { combat_role: 'Melee' },
    'Barbed Devil': { combat_role: 'Melee' },
    'Bat': { combat_role: 'Melee' },
    'Bearded Devil': { combat_role: 'Melee' },
    'Behir': { combat_role: 'Ranged' },
    'Berserker': { combat_role: 'Melee' },
    'Black Bear': { combat_role: 'Melee' },
    'Black Dragon Wyrmling': { combat_role: 'Ranged' },
    'Blink Dog': { combat_role: 'Melee' },
    'Blood Hawk': { combat_role: 'Melee' },
    'Blue Dragon Wyrmling': { combat_role: 'Ranged' },
    'Boar': { combat_role: 'Melee' },
    'Bone Devil': { combat_role: 'Melee' },
    'Brass Dragon Wyrmling': { combat_role: 'Ranged' },
    'Bronze Dragon Wyrmling': { combat_role: 'Ranged' },
    'Brown Bear': { combat_role: 'Melee' },
    'Camel': { combat_role: 'Melee' },
    'Cat': { combat_role: 'Melee' },
    'Centaur': { combat_role: 'Ranged' },
    'Chain Devil': { combat_role: 'Melee' },
    'Chimera': { combat_role: 'Ranged' },
    'Chuul': { combat_role: 'Melee' },
    'Clay Golem': { combat_role: 'Melee' },
    'Cloud Giant': { combat_role: 'Ranged' },
    'Cockatrice': { combat_role: 'Melee' },
    'Commoner': { combat_role: 'Melee' },
    'Constrictor Snake': { combat_role: 'Melee' },
    'Copper Dragon Wyrmling': { combat_role: 'Ranged' },
    'Couatl': { combat_role: 'Ranged' },
    'Crab': { combat_role: 'Melee' },
    'Crocodile': { combat_role: 'Melee' },
    'Cult Fanatic': { combat_role: 'Ranged' },
    'Darkmantle': { combat_role: 'Melee' },
    'Death Dog': { combat_role: 'Melee' },
    'Deep Gnome (Svirfneblin)': { combat_role: 'Ranged' },
    'Deer': { combat_role: 'Melee' },
    'Deva': { combat_role: 'Ranged' },
    'Dire Wolf': { combat_role: 'Melee' },
    'Djinni': { combat_role: 'Ranged' },
    'Doppelganger': { combat_role: 'Melee' },
    'Draft Horse': { combat_role: 'Melee' },
    'Dragon Turtle': { combat_role: 'Ranged' },
    'Dretch': { combat_role: 'Melee' },
    'Drider': { combat_role: 'Ranged' },
    'Drow': { combat_role: 'Ranged' },
    'Dryad': { combat_role: 'Ranged' },
    'Duergar': { combat_role: 'Ranged' },
    'Dust Mephit': { combat_role: 'Ranged' },
    'Eagle': { combat_role: 'Melee' },
    'Earth Elemental': { combat_role: 'Melee' },
    'Efreeti': { combat_role: 'Ranged' },
    'Elephant': { combat_role: 'Melee' },
    'Elk': { combat_role: 'Melee' },
    'Erinyes': { combat_role: 'Ranged' },
    'Ettin': { combat_role: 'Melee' },
    'Fire Elemental': { combat_role: 'Melee' },
    'Fire Giant': { combat_role: 'Ranged' },
    'Flesh Golem': { combat_role: 'Melee' },
    'Flying Snake': { combat_role: 'Melee' },
    'Flying Sword': { combat_role: 'Melee' },
    'Frog': { combat_role: 'Melee' },
    'Frost Giant': { combat_role: 'Ranged' },
    'Gargoyle': { combat_role: 'Melee' },
    'Gelatinous Cube': { combat_role: 'Melee' },
    'Ghast': { combat_role: 'Melee' },
    'Ghost': { combat_role: 'Melee' },
    'Giant Ape': { combat_role: 'Ranged' },
    'Giant Badger': { combat_role: 'Melee' },
    'Giant Bat': { combat_role: 'Melee' },
    'Giant Boar': { combat_role: 'Melee' },
    'Giant Centipede': { combat_role: 'Melee' },
    'Giant Constrictor Snake': { combat_role: 'Melee' },
    'Giant Crab': { combat_role: 'Melee' },
    'Giant Crocodile': { combat_role: 'Melee' },
    'Giant Eagle': { combat_role: 'Melee' },
    'Giant Elk': { combat_role: 'Melee' },
    'Giant Fire Beetle': { combat_role: 'Melee' },
    'Giant Frog': { combat_role: 'Melee' },
    'Giant Goat': { combat_role: 'Melee' },
    'Giant Hyena': { combat_role: 'Melee' },
    'Giant Lizard': { combat_role: 'Melee' },
    'Giant Octopus': { combat_role: 'Melee' },
    'Giant Owl': { combat_role: 'Melee' },
    'Giant Poisonous Snake': { combat_role: 'Melee' },
    'Giant Rat': { combat_role: 'Melee' },
    'Giant Rat (Diseased)': { combat_role: 'Melee' },
    'Giant Scorpion': { combat_role: 'Melee' },
    'Giant Sea Horse': { combat_role: 'Melee' },
    'Giant Shark': { combat_role: 'Melee' },
    'Giant Toad': { combat_role: 'Melee' },
    'Giant Vulture': { combat_role: 'Melee' },
    'Giant Wasp': { combat_role: 'Melee' },
    'Giant Weasel': { combat_role: 'Melee' },
    'Giant Wolf Spider': { combat_role: 'Melee' },
    'Gibbering Mouther': { combat_role: 'Melee' },
    'Gladiator': { combat_role: 'Ranged' },
    'Goat': { combat_role: 'Melee' },
    'Gold Dragon Wyrmling': { combat_role: 'Ranged' },
    'Gorgon': { combat_role: 'Ranged' },
    'Green Dragon Wyrmling': { combat_role: 'Ranged' },
    'Green Hag': { combat_role: 'Ranged' },
    'Grick': { combat_role: 'Melee' },
    'Grimlock': { combat_role: 'Melee' },
    'Guard': { combat_role: 'Ranged' },
    'Guardian Naga': { combat_role: 'Ranged' },
    'Gynosphinx': { combat_role: 'Ranged' },
    'Half-Red Dragon Veteran': { combat_role: 'Ranged' },
    'Harpy': { combat_role: 'Melee' },
    'Hawk': { combat_role: 'Melee' },

    // ============================= D&D SRD MONSTERS (17 names shared with Nimble, added in facet-data remediation) =============================
    'Bandit': { combat_role: 'Ranged' },
    'Bandit Captain': { combat_role: 'Ranged' },
    'Basilisk': { combat_role: 'Melee' },
    'Black Pudding': { combat_role: 'Melee' },
    'Bugbear': { combat_role: 'Ranged' },
    'Bulette': { combat_role: 'Melee' },
    'Cloaker': { combat_role: 'Melee' },
    'Cultist': { combat_role: 'Melee' },
    'Druid': { combat_role: 'Ranged' },
    'Ettercap': { combat_role: 'Ranged' },
    'Ghoul': { combat_role: 'Melee' },
    'Giant Spider': { combat_role: 'Ranged' },
    'Glabrezu': { combat_role: 'Ranged' },
    'Gnoll': { combat_role: 'Ranged' },
    'Goblin': { combat_role: 'Ranged' },
    'Gray Ooze': { combat_role: 'Melee' },
    'Griffon': { combat_role: 'Melee' },

    // ============================= D&D SRD MONSTERS (Hell Hound–Kraken, batch B2) =============================
    'Hell Hound': { combat_role: 'Ranged' },
    'Hezrou': { combat_role: 'Melee' },
    'Hill Giant': { combat_role: 'Ranged' },
    'Hippogriff': { combat_role: 'Melee' },
    'Hobgoblin': { combat_role: 'Ranged' },
    'Homunculus': { combat_role: 'Melee' },
    'Horned Devil': { combat_role: 'Ranged' },
    'Hunter Shark': { combat_role: 'Melee' },
    'Hydra': { combat_role: 'Melee' },
    'Hyena': { combat_role: 'Melee' },
    'Ice Devil': { combat_role: 'Melee' },
    'Ice Mephit': { combat_role: 'Ranged' },
    'Imp': { combat_role: 'Melee' },
    'Invisible Stalker': { combat_role: 'Melee' },
    'Iron Golem': { combat_role: 'Ranged' },
    'Jackal': { combat_role: 'Melee' },
    'Killer Whale': { combat_role: 'Melee' },
    'Knight': { combat_role: 'Ranged' },
    'Kobold': { combat_role: 'Ranged' },
    'Kraken': { combat_role: 'Ranged' },

    // ============================= D&D SRD MONSTERS (Lamia–Nightmare, batch B2) =============================
    'Lamia': { combat_role: 'Melee' },
    'Lemure': { combat_role: 'Melee' },
    'Lich': { combat_role: 'Ranged' },
    'Lion': { combat_role: 'Melee' },
    'Lizard': { combat_role: 'Melee' },
    'Lizardfolk': { combat_role: 'Ranged' },
    'Mage': { combat_role: 'Ranged' },
    'Magma Mephit': { combat_role: 'Ranged' },
    'Magmin': { combat_role: 'Melee' },
    'Mammoth': { combat_role: 'Melee' },
    'Manticore': { combat_role: 'Ranged' },
    'Marilith': { combat_role: 'Melee' },
    'Mastiff': { combat_role: 'Melee' },
    'Medusa': { combat_role: 'Ranged' },
    'Merfolk': { combat_role: 'Ranged' },
    'Merrow': { combat_role: 'Ranged' },
    'Mimic': { combat_role: 'Melee' },
    'Minotaur': { combat_role: 'Melee' },
    'Minotaur Skeleton': { combat_role: 'Melee' },
    'Mule': { combat_role: 'Melee' },
    'Mummy': { combat_role: 'Melee' },
    'Mummy Lord': { combat_role: 'Ranged' },
    'Nalfeshnee': { combat_role: 'Melee' },
    'Night Hag': { combat_role: 'Ranged' },
    'Nightmare': { combat_role: 'Melee' },

    // ============================= D&D SRD MONSTERS (Noble–Rakshasa, batch B2) =============================
    'Noble': { combat_role: 'Melee' },
    'Ochre Jelly': { combat_role: 'Melee' },
    'Octopus': { combat_role: 'Melee' },
    'Ogre': { combat_role: 'Melee' },
    'Ogre Zombie': { combat_role: 'Melee' },
    'Oni': { combat_role: 'Ranged' },
    'Orc': { combat_role: 'Ranged' },
    'Otyugh': { combat_role: 'Melee' },
    'Owl': { combat_role: 'Melee' },
    'Owlbear': { combat_role: 'Melee' },
    'Panther': { combat_role: 'Melee' },
    'Pegasus': { combat_role: 'Melee' },
    'Phase Spider': { combat_role: 'Melee' },
    'Pit Fiend': { combat_role: 'Ranged' },
    'Planetar': { combat_role: 'Ranged' },
    'Plesiosaurus': { combat_role: 'Melee' },
    'Poisonous Snake': { combat_role: 'Melee' },
    'Polar Bear': { combat_role: 'Melee' },
    'Pony': { combat_role: 'Melee' },
    'Priest': { combat_role: 'Ranged' },
    'Pseudodragon': { combat_role: 'Melee' },
    'Purple Worm': { combat_role: 'Melee' },
    'Quasit': { combat_role: 'Melee' },
    'Quipper': { combat_role: 'Melee' },
    'Rakshasa': { combat_role: 'Ranged' },

    // ============================= D&D SRD MONSTERS (Rat–Skeleton, batch B2) =============================
    'Rat': { combat_role: 'Melee' },
    'Raven': { combat_role: 'Melee' },
    'Red Dragon Wyrmling': { combat_role: 'Ranged' },
    'Reef Shark': { combat_role: 'Melee' },
    'Remorhaz': { combat_role: 'Melee' },
    'Rhinoceros': { combat_role: 'Melee' },
    'Riding Horse': { combat_role: 'Melee' },
    'Roc': { combat_role: 'Melee' },
    'Roper': { combat_role: 'Melee' },
    'Rug of Smothering': { combat_role: 'Melee' },
    'Rust Monster': { combat_role: 'Melee' },
    'Saber-Toothed Tiger': { combat_role: 'Melee' },
    'Sahuagin': { combat_role: 'Ranged' },
    'Salamander': { combat_role: 'Ranged' },
    'Satyr': { combat_role: 'Ranged' },
    'Scorpion': { combat_role: 'Melee' },
    'Scout': { combat_role: 'Ranged' },
    'Sea Hag': { combat_role: 'Melee' },
    'Sea Horse': { combat_role: 'Melee' },
    'Shadow': { combat_role: 'Melee' },
    'Shambling Mound': { combat_role: 'Melee' },
    'Shield Guardian': { combat_role: 'Melee' },
    'Shrieker': { combat_role: 'Melee' },
    'Silver Dragon Wyrmling': { combat_role: 'Ranged' },
    'Skeleton': { combat_role: 'Ranged' },

    // ============================= D&D SRD MONSTERS (Solar–Tiger, batch B2) =============================
    'Solar': { combat_role: 'Ranged' },
    'Specter': { combat_role: 'Melee' },
    'Spider': { combat_role: 'Melee' },
    'Spirit Naga': { combat_role: 'Ranged' },
    'Sprite': { combat_role: 'Ranged' },
    'Spy': { combat_role: 'Ranged' },
    'Steam Mephit': { combat_role: 'Ranged' },
    'Stirge': { combat_role: 'Melee' },
    'Stone Giant': { combat_role: 'Ranged' },
    'Stone Golem': { combat_role: 'Ranged' },
    'Storm Giant': { combat_role: 'Ranged' },
    'Succubus/Incubus': { combat_role: 'Melee' },
    'Swarm of Bats': { combat_role: 'Melee' },
    'Swarm of Beetles': { combat_role: 'Melee' },
    'Swarm of Centipedes': { combat_role: 'Melee' },
    'Swarm of Insects': { combat_role: 'Melee' },
    'Swarm of Poisonous Snakes': { combat_role: 'Melee' },
    'Swarm of Quippers': { combat_role: 'Melee' },
    'Swarm of Rats': { combat_role: 'Melee' },
    'Swarm of Ravens': { combat_role: 'Melee' },
    'Swarm of Spiders': { combat_role: 'Melee' },
    'Swarm of Wasps': { combat_role: 'Melee' },
    'Tarrasque': { combat_role: 'Melee' },
    'Thug': { combat_role: 'Ranged' },
    'Tiger': { combat_role: 'Melee' },

    // ============================= D&D SRD MONSTERS (Treant–Zombie, batch B2) =============================
    'Treant': { combat_role: 'Ranged' },
    'Tribal Warrior': { combat_role: 'Ranged' },
    'Triceratops': { combat_role: 'Melee' },
    'Troll': { combat_role: 'Melee' },
    'Tyrannosaurus Rex': { combat_role: 'Melee' },
    'Unicorn': { combat_role: 'Melee' },
    'Vampire': { combat_role: 'Melee' },
    'Vampire Spawn': { combat_role: 'Melee' },
    'Veteran': { combat_role: 'Ranged' },
    'Violet Fungus': { combat_role: 'Melee' },
    'Vrock': { combat_role: 'Melee' },
    'Vulture': { combat_role: 'Melee' },
    'Warhorse': { combat_role: 'Melee' },
    'Warhorse Skeleton': { combat_role: 'Melee' },
    'Water Elemental': { combat_role: 'Melee' },
    'Weasel': { combat_role: 'Melee' },
    'Werebear': { combat_role: 'Melee' },
    'Wereboar': { combat_role: 'Melee' },
    'Wererat': { combat_role: 'Ranged' },
    'Weretiger': { combat_role: 'Melee' },
    'Werewolf': { combat_role: 'Melee' },
    'White Dragon Wyrmling': { combat_role: 'Ranged' },
    'Wight': { combat_role: 'Ranged' },
    "Will-o'-Wisp": { combat_role: 'Melee' },
    'Winter Wolf': { combat_role: 'Ranged' },
    'Wolf': { combat_role: 'Melee' },
    'Worg': { combat_role: 'Melee' },
    'Wraith': { combat_role: 'Melee' },
    'Wyvern': { combat_role: 'Melee' },
    'Xorn': { combat_role: 'Melee' },
    'Young Black Dragon': { combat_role: 'Ranged' },
    'Young Blue Dragon': { combat_role: 'Ranged' },
    'Young Brass Dragon': { combat_role: 'Ranged' },
    'Young Bronze Dragon': { combat_role: 'Ranged' },
    'Young Copper Dragon': { combat_role: 'Ranged' },
    'Young Gold Dragon': { combat_role: 'Ranged' },
    'Young Green Dragon': { combat_role: 'Ranged' },
    'Young Red Dragon': { combat_role: 'Ranged' },
    'Young Silver Dragon': { combat_role: 'Ranged' },
    'Young White Dragon': { combat_role: 'Ranged' },
    'Zombie': { combat_role: 'Melee' },
  },
};

// Nimble spell mana costs, derived from each spell's `level` field in
// scripts/seed-nimble-spells.ts: 'Cantrip' -> 0, 'Tier N' -> N. Spell names
// are unique across the whole spell list, so this is a single flat map.
export const JUDGMENT_SPELL_MANA_COST: Record<string, number> = {
  // Fire
  'Flame Dart': 0,
  "Heart's Fire": 0,
  Ignite: 1,
  'Enchant Weapon': 2,
  'Flame Barrier': 3,
  Pyroclasm: 4,
  'Fiery Embrace': 5,
  'Living Inferno': 7,
  Dragonform: 9,

  // Ice
  'Ice Lance': 0,
  Snowblind: 0,
  'Frost Shield': 1,
  Shatter: 2,
  Cryosleep: 3,
  Rimeblades: 4,
  'Arctic Blast': 5,
  'Glacier Strike': 8,
  'Arctic Annihilation': 9,

  // Lightning
  Zap: 0,
  Overload: 0,
  'Arc Lightning': 1,
  Alacrity: 2,
  Stormlash: 3,
  Electrickery: 4,
  Electrocharge: 5,
  'Ride the Lightning': 6,
  'Seething Storm': 9,

  // Wind
  'Razor Wind': 0,
  'Breath of Life': 0,
  'Blustery Gale': 1,
  'Barrier of Wind': 2,
  Fly: 3,
  'Eye of the Storm': 4,
  Updraft: 5,
  'Thousand Cuts': 6,
  'Boisterous Winds': 7,
  'Vicious Mockery': 0,

  // Radiant
  Rebuke: 0,
  'True Strike': 0,
  Heal: 1,
  'Warding Bond': 2,
  'Shield of Justice': 3,
  Condemn: 4,
  Vengeance: 5,
  Sacrifice: 6,
  Redeem: 9,
  'Lifebinding Spirit': 1,

  // Necrotic
  Entice: 0,
  'Withering Touch': 0,
  'Shadow Trap': 1,
  'Dread Visage': 2,
  'Vampiric Greed': 3,
  'Greater Shadow': 4,
  'Gangrenous Burst': 5,
  'Unspeakable Word': 6,
  'Creeping Death': 7,
  'Shadow Blast': 0,
  'Summon Shadow': 0,

  // Utility: Ice
  'Ice Disk': 0,
  Chillcraft: 0,
  'Wintry Scrying': 0,

  // Utility: Lightning
  'Spark Buddy': 0,
  'Spark Step': 0,
  "Tempest's Command": 0,

  // Utility: Radiant
  Light: 0,
  Beautify: 0,
  'Bond of Peace': 0,

  // Utility: Fire
  Firebrand: 0,
  'Fire Step': 0,
  Kindle: 0,

  // Utility: Wind
  'Wind Whisper': 0,
  'Helpful Gust': 0,
  'Feather Fall': 0,

  // Utility: Necrotic
  Gravecraft: 0,
  'False Face': 0,
  'Thought Leech': 0,
};
