import { createSupabaseClient } from '../lib/supabase/client';
import { createItem, type ItemInput } from '../lib/content/items';

const SYSTEM_ID = 'f9f3ee85-7dc8-4db9-a0e8-4a818462f056'; // Nimble
const CORE_RULES_SOURCE_ID = '75824afb-fb75-46a6-886e-f0f8320e4600'; // Core Rules
const FEY_SOURCE_ID = 'e2029979-d16f-40c4-a38c-4466b0c4df7f'; // Fey
const BUGS_SOURCE_ID = '803cab3f-5ae0-48be-a61b-c9c33303dea0'; // Giant Bugs

type RawItem = Omit<ItemInput, 'system_id' | 'source_id' | 'is_homebrew'>;

function coreItem(item: RawItem): ItemInput {
  return { ...item, system_id: SYSTEM_ID, source_id: CORE_RULES_SOURCE_ID, is_homebrew: false };
}

function feyItem(item: RawItem): ItemInput {
  return { ...item, system_id: SYSTEM_ID, source_id: FEY_SOURCE_ID, is_homebrew: false };
}

function bugItem(item: RawItem): ItemInput {
  return { ...item, system_id: SYSTEM_ID, source_id: BUGS_SOURCE_ID, is_homebrew: false };
}

const CORE_RULES_ITEMS: RawItem[] = [
  // --- Armor: Cloth ---
  {
    name: "Adventurer's Garb",
    item_type: 'Armor',
    rarity: 'Common',
    tags: ['Armor', 'Cloth'],
    description: 'Simple cloth armor for the traveling adventurer. Armor: 2+DEX. Cost: 10 gp.',
    stats: { Armor: '2+DEX', Cost: '10 gp' },
  },
  {
    name: 'Minor Enchantment',
    item_type: 'Armor',
    rarity: 'Uncommon',
    tags: ['Armor', 'Cloth'],
    description: 'Lightly enchanted cloth robes that bolster the wearer against harm. Armor: 3+DEX. Cost: 100 gp.',
    stats: { Armor: '3+DEX', Cost: '100 gp' },
  },
  {
    name: 'Major Enchantment',
    item_type: 'Armor',
    rarity: 'Rare',
    tags: ['Armor', 'Cloth'],
    description: 'Cloth armor woven through with potent protective enchantments. Armor: 4+DEX. Cost: 1,000 gp.',
    stats: { Armor: '4+DEX', Cost: '1,000 gp' },
  },
  {
    name: 'Epic Enchantment',
    item_type: 'Armor',
    rarity: 'Very Rare',
    tags: ['Armor', 'Cloth'],
    description: 'The pinnacle of enchanted cloth armor, rivaling steel plate in protection while weighing almost nothing. Armor: 5+DEX. Cost: 10,000 gp.',
    stats: { Armor: '5+DEX', Cost: '10,000 gp' },
  },
  // --- Armor: Leather ---
  {
    name: 'Cheap Hides',
    item_type: 'Armor',
    rarity: 'Common',
    tags: ['Armor', 'Leather'],
    description: 'Roughly cured animal hides, stitched into a serviceable if unrefined layer of protection. Armor: 3+DEX. Cost: 5 gp.',
    stats: { Armor: '3+DEX', Cost: '5 gp' },
  },
  {
    name: 'Ox Hide',
    item_type: 'Armor',
    rarity: 'Common',
    tags: ['Armor', 'Leather'],
    description: 'Thick, well-cured leather armor made from ox hide. Armor: 4+DEX. Cost: 45 gp.',
    stats: { Armor: '4+DEX', Cost: '45 gp' },
  },
  {
    name: 'Hard Leather',
    item_type: 'Armor',
    rarity: 'Uncommon',
    tags: ['Armor', 'Leather'],
    description: 'Boiled and hardened leather armor. Requires 1 STR. Armor: 5+DEX. Cost: 300 gp.',
    stats: { Armor: '5+DEX', Requirement: 'Req. 1 STR', Cost: '300 gp' },
  },
  {
    name: 'Wyrmhide',
    item_type: 'Armor',
    rarity: 'Rare',
    tags: ['Armor', 'Leather'],
    description: 'Armor crafted from the tough, scaled hide of a dragon or wyrm. Requires 1 STR. Armor: 6+DEX. Cost: 2,000 gp.',
    stats: { Armor: '6+DEX', Requirement: 'Req. 1 STR', Cost: '2,000 gp' },
  },
  // --- Armor: Mail ---
  {
    name: 'Rusty Mail',
    item_type: 'Armor',
    rarity: 'Common',
    tags: ['Armor', 'Mail'],
    description: 'Old, pitted chainmail that has seen better days but still turns a blade. Armor: 6+DEX (max 2). Cost: 15 gp.',
    stats: { Armor: '6+DEX (max 2)', Cost: '15 gp' },
  },
  {
    name: 'Chain Shirt',
    item_type: 'Armor',
    rarity: 'Uncommon',
    tags: ['Armor', 'Mail'],
    description: 'A well-made shirt of interlocking metal rings. Requires 2 STR. Armor: 9+DEX (max 2). Cost: 60 gp.',
    stats: { Armor: '9+DEX (max 2)', Requirement: 'Req. 2 STR', Cost: '60 gp' },
  },
  {
    name: 'Scale Mail',
    item_type: 'Armor',
    rarity: 'Rare',
    tags: ['Armor', 'Mail'],
    description: 'Overlapping metal scales layered over a leather backing. Requires 3 STR. Armor: 12+DEX (max 2). Cost: 700 gp.',
    stats: { Armor: '12+DEX (max 2)', Requirement: 'Req. 3 STR', Cost: '700 gp' },
  },
  {
    name: 'Dragonscale',
    item_type: 'Armor',
    rarity: 'Very Rare',
    tags: ['Armor', 'Mail'],
    description: 'Mail woven from actual dragon scales, prized for both its protection and its prestige. Requires 4 STR. Armor: 15+DEX (max 2). Cost: 3,000 gp.',
    stats: { Armor: '15+DEX (max 2)', Requirement: 'Req. 4 STR', Cost: '3,000 gp' },
  },
  // --- Armor: Plate ---
  {
    name: 'Rusty Plate',
    item_type: 'Armor',
    rarity: 'Common',
    tags: ['Armor', 'Plate'],
    description: 'Battered old plate armor. Heavy and unwieldy, but sturdy. Requires 2 STR. Armor: 10 (flat, not DEX-modified). Cost: 25 gp.',
    stats: { Armor: '10', Requirement: 'Req. 2 STR', Cost: '25 gp' },
  },
  {
    name: 'Half Plate',
    item_type: 'Armor',
    rarity: 'Uncommon',
    tags: ['Armor', 'Plate'],
    description: 'Partial plate armor covering the vital areas of the body. Requires 3 STR. Armor: 14 (flat). Cost: 200 gp.',
    stats: { Armor: '14', Requirement: 'Req. 3 STR', Cost: '200 gp' },
  },
  {
    name: 'Full Plate',
    item_type: 'Armor',
    rarity: 'Rare',
    tags: ['Armor', 'Plate'],
    description: 'A complete suit of articulated steel plate. Requires 4 STR. Armor: 18 (flat). Cost: 2,000 gp.',
    stats: { Armor: '18', Requirement: 'Req. 4 STR', Cost: '2,000 gp' },
  },
  {
    name: 'Mithril Plate',
    item_type: 'Armor',
    rarity: 'Very Rare',
    tags: ['Armor', 'Plate'],
    description: 'Full plate forged from priceless mithril, combining the protection of steel with a fraction of the weight. Requires 5 STR. Armor: 22 (flat). Cost: 5,000 gp.',
    stats: { Armor: '22', Requirement: 'Req. 5 STR', Cost: '5,000 gp' },
  },
  // --- Shields ---
  {
    name: 'Wooden Buckler',
    item_type: 'Shield',
    rarity: 'Common',
    tags: ['Shield'],
    description: 'A small round shield of simple wood construction. Armor: +2. Cost: 5 gp.',
    stats: { Armor: '2', Cost: '5 gp' },
  },
  {
    name: 'Iron Shield',
    item_type: 'Shield',
    rarity: 'Uncommon',
    tags: ['Shield'],
    description: 'A solid shield banded in iron. Requires 2 STR. Armor: +4. Cost: 80 gp.',
    stats: { Armor: '4', Requirement: 'Req. 2 STR', Cost: '80 gp' },
  },
  {
    name: 'Tower Shield',
    item_type: 'Shield',
    rarity: 'Rare',
    tags: ['Shield'],
    description: 'A massive shield capable of covering nearly the entire body. Requires 3 STR. Armor: +6. Cost: 1,500 gp.',
    stats: { Armor: '6', Requirement: 'Req. 3 STR', Cost: '1,500 gp' },
  },
  {
    name: 'Dragon Shield',
    item_type: 'Shield',
    rarity: 'Very Rare',
    tags: ['Shield'],
    description: 'A shield forged from dragon-scale and bone, as much a trophy as it is protection. Requires 3 STR. Armor: +8. Cost: 9,000 gp.',
    stats: { Armor: '8', Requirement: 'Req. 3 STR', Cost: '9,000 gp' },
  },
  // --- Melee Weapons ---
  {
    name: 'Dagger',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A small, quick blade. Damage: 1d4+DEX Piercing. Properties: Light, Thrown 4. Cost: 3 gp.',
    stats: { Damage: '1d4+DEX Piercing', Properties: 'Light, Thrown 4', Cost: '3 gp' },
  },
  {
    name: 'Sickle',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A curved farming tool turned weapon. Damage: 1d4+DEX Slashing. Properties: Vicious (roll an additional die on crit damage). Cost: 10 gp.',
    stats: { Damage: '1d4+DEX Slashing', Properties: 'Vicious', Cost: '10 gp' },
  },
  {
    name: 'Club/Mace',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A simple blunt weapon, from a rough club to a metal-headed mace. Damage: 1d6+STR Bludgeoning. Cost: 2 gp.',
    stats: { Damage: '1d6+STR Bludgeoning', Cost: '2 gp' },
  },
  {
    name: 'Hand Axe',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A small axe that can be swung or thrown. Damage: 1d6+STR Slashing. Properties: Thrown 4. Cost: 8 gp.',
    stats: { Damage: '1d6+STR Slashing', Properties: 'Thrown 4', Cost: '8 gp' },
  },
  {
    name: 'Short Sword',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A light, quick blade suited to dual wielding. Damage: 1d6+DEX Piercing. Properties: Light. Cost: 10 gp.',
    stats: { Damage: '1d6+DEX Piercing', Properties: 'Light', Cost: '10 gp' },
  },
  {
    name: 'Rapier',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A slender, finesse-oriented thrusting blade. Damage: 2d4+DEX Piercing. Cost: 60 gp.',
    stats: { Damage: '2d4+DEX Piercing', Cost: '60 gp' },
  },
  {
    name: 'Staff',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A long wooden staff, favored by wandering scholars and spellcasters. Damage: 1d8+STR Bludgeoning. Properties: 2-handed. Cost: 8 gp.',
    stats: { Damage: '1d8+STR Bludgeoning', Properties: '2-handed', Cost: '8 gp' },
  },
  {
    name: 'Longsword',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A classic double-edged blade. Damage: 1d8+STR Slashing. Properties: 2-handed (1-handed: Req. 2 STR). Cost: 60 gp.',
    stats: { Damage: '1d8+STR Slashing', Properties: '2-handed (1-handed: Req. 2 STR)', Cost: '60 gp' },
  },
  {
    name: 'Battleaxe',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A heavy, broad-bladed axe. Damage: 1d10+STR Slashing. Properties: 2-handed. Cost: 30 gp.',
    stats: { Damage: '1d10+STR Slashing', Properties: '2-handed', Cost: '30 gp' },
  },
  {
    name: 'Pole Hammer',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A long-hafted hammer that keeps enemies at bay. Damage: 1d10+STR Bludgeoning. Properties: 2-handed, Reach 2. Cost: 60 gp.',
    stats: { Damage: '1d10+STR Bludgeoning', Properties: '2-handed, Reach 2', Cost: '60 gp' },
  },
  {
    name: 'Glaive',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A blade mounted on a long pole. Damage: 1d10+STR Slashing. Properties: 2-handed, Reach 2. Cost: 60 gp.',
    stats: { Damage: '1d10+STR Slashing', Properties: '2-handed, Reach 2', Cost: '60 gp' },
  },
  {
    name: 'Spear',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A simple, versatile thrusting weapon. Damage: 1d10+STR Piercing. Properties: 2-handed, Reach 2. Cost: 60 gp.',
    stats: { Damage: '1d10+STR Piercing', Properties: '2-handed, Reach 2', Cost: '60 gp' },
  },
  {
    name: 'Greatmaul',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A massive, crushing two-handed hammer. Damage: 1d12+STR Bludgeoning. Properties: 2-handed (Req. 2 STR). Cost: 80 gp.',
    stats: { Damage: '1d12+STR Bludgeoning', Properties: '2-handed (Req. 2 STR)', Cost: '80 gp' },
  },
  {
    name: 'Greataxe',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A massive two-handed axe. Damage: 2d6+STR Slashing. Properties: 2-handed (Req. 2 STR). Cost: 100 gp.',
    stats: { Damage: '2d6+STR Slashing', Properties: '2-handed (Req. 2 STR)', Cost: '100 gp' },
  },
  {
    name: 'Greatsword',
    item_type: 'Melee Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Melee'],
    description: 'A massive two-handed sword. Damage: 3d4+STR Slashing/Piercing. Properties: 2-handed (Req. 2 STR). Cost: 120 gp.',
    stats: { Damage: '3d4+STR Slashing/Piercing', Properties: '2-handed (Req. 2 STR)', Cost: '120 gp' },
  },
  // --- Ranged Weapons ---
  {
    name: 'Sling',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'A simple leather sling for hurling stones. Damage: 1d4+DEX Bludgeoning. Properties: 2-handed, Range 12, Vicious. Cost: 4 gp.',
    stats: { Damage: '1d4+DEX Bludgeoning', Properties: '2-handed, Range 12, Vicious', Cost: '4 gp' },
  },
  {
    name: 'Javelins',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'Light throwing spears sold in bundles. Damage: 1d6+STR Piercing. Properties: Range 8, Stack of 4. Cost: 20 gp.',
    stats: { Damage: '1d6+STR Piercing', Properties: 'Range 8, Stack of 4', Cost: '20 gp' },
  },
  {
    name: 'Throwing Hammers',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'Balanced hammers meant to be thrown. Damage: 1d8+STR Bludgeoning. Properties: Range 4, Stack of 3. Cost: 25 gp.',
    stats: { Damage: '1d8+STR Bludgeoning', Properties: 'Range 4, Stack of 3', Cost: '25 gp' },
  },
  {
    name: 'Shortbow',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'A compact bow, easy to wield. Damage: 1d6+DEX Piercing. Properties: 2-handed, Range 12. Cost: 25 gp.',
    stats: { Damage: '1d6+DEX Piercing', Properties: '2-handed, Range 12', Cost: '25 gp' },
  },
  {
    name: 'Longbow',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'A tall, powerful bow with excellent range. Requires 1 STR. Damage: 1d8+DEX Piercing. Properties: 2-handed, Range 16 (Req. 1 STR). Cost: 30 gp.',
    stats: { Damage: '1d8+DEX Piercing', Properties: '2-handed, Range 16 (Req. 1 STR)', Cost: '30 gp' },
  },
  {
    name: 'Crossbow',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'A mechanical bow that hits hard but must be reloaded. Damage: 4d4+DEX Piercing. Properties: 2-handed, Load: 1 action, Range 8. Cost: 60 gp.',
    stats: { Damage: '4d4+DEX Piercing', Properties: '2-handed, Load: 1 action, Range 8', Cost: '60 gp' },
  },
  {
    name: 'Handheld Ballista',
    item_type: 'Ranged Weapon',
    rarity: 'Common',
    tags: ['Weapon', 'Ranged'],
    description: 'An oversized, devastating hand-cranked ballista. Requires 2 STR. Damage: 1d20+DEX Piercing. Properties: 2-handed, Load: 2 actions, Range 8 (Req. 2 STR). Cost: 120 gp.',
    stats: { Damage: '1d20+DEX Piercing', Properties: '2-handed, Load: 2 actions, Range 8 (Req. 2 STR)', Cost: '120 gp' },
  },
  // --- Misc Adventuring Equipment ---
  {
    name: 'Healing Potion',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear', 'Potion'],
    description: 'A shimmering red elixir. Action: Heal 2d4+4 HP. Cost: 50 gp.',
    stats: { Effect: '(action) Heal 2d4+4 HP.', Cost: '50 gp' },
  },
  {
    name: 'Greater Healing Potion',
    item_type: 'Adventuring Gear',
    rarity: 'Uncommon',
    tags: ['Adventuring Gear', 'Potion'],
    description: 'A stronger version of the standard healing potion. Action: Heal 3d6+6 HP. Cost: 150 gp.',
    stats: { Effect: '(action) Heal 3d6+6 HP.', Cost: '150 gp' },
  },
  {
    name: 'Supreme Healing Potion',
    item_type: 'Adventuring Gear',
    rarity: 'Rare',
    tags: ['Adventuring Gear', 'Potion'],
    description: 'The most potent commonly-brewed healing draught. Action: Heal 4d8+8 HP. Cost: 450 gp.',
    stats: { Effect: '(action) Heal 4d8+8 HP.', Cost: '450 gp' },
  },
  {
    name: 'Torch (stack of 2)',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear', 'Light'],
    description: 'For when it is dark. 1 use each, casts light up to 6 spaces. Cost: 5 sp.',
    stats: { Properties: 'For when it’s dark. 1 use each.', Cost: '5 sp' },
  },
  {
    name: 'Lantern & Oil',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear', 'Light'],
    description: 'Like a torch, but not as cool. Refill costs 1 gp. Cost: 10 gp.',
    stats: { Properties: 'Like a torch, but not as cool (refill: 1 gp).', Cost: '10 gp' },
  },
  {
    name: 'Vial of Pitch',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Sticky, and VERY flammable. Cost: 2 gp.',
    stats: { Properties: 'Sticky, and VERY flammable.', Cost: '2 gp' },
  },
  {
    name: 'Rope (50 ft.)',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'You always need rope. Cost: 10 gp.',
    stats: { Properties: 'You always need rope.', Cost: '10 gp' },
  },
  {
    name: 'Chain (10 ft.)',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Like rope, but stronger (and heavy). Cost: 50 gp.',
    stats: { Properties: 'Like rope, but stronger (and heavy).', Cost: '50 gp' },
  },
  {
    name: 'Bucket',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Also works as a hat in a pinch! Cost: 1 gp.',
    stats: { Properties: 'Also works as a hat in a pinch!', Cost: '1 gp' },
  },
  {
    name: 'Padlock & Key',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Lock it or lose it. Cost: 3 gp.',
    stats: { Properties: 'Lock it or lose it.', Cost: '3 gp' },
  },
  {
    name: 'Mirror',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'For medusas AND spinach teeth. Cost: 4 gp.',
    stats: { Properties: 'For medusas AND spinach teeth.', Cost: '4 gp' },
  },
  {
    name: 'Telescope',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Arrr. Cost: 10 gp.',
    stats: { Properties: 'Arrr.', Cost: '10 gp' },
  },
  {
    name: 'Magnifying Glass',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Make the small, big. Cost: 5 gp.',
    stats: { Properties: 'Make the small, big.', Cost: '5 gp' },
  },
  {
    name: 'Chalk',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Not JUST for kids. Cost: 1 sp.',
    stats: { Properties: 'Not JUST for kids.', Cost: '1 sp' },
  },
  {
    name: 'Shovel',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Sometimes you need a hole dug. Cost: 3 gp.',
    stats: { Properties: 'Sometimes you need a hole dug.', Cost: '3 gp' },
  },
  {
    name: 'Pulley',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Pull down, go up. Cost: 3 gp.',
    stats: { Properties: 'Pull down, go up.', Cost: '3 gp' },
  },
  {
    name: 'Grappling Hook',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'For climbing or catching BIG fish. Cost: 4 gp.',
    stats: { Properties: 'For climbing or catching BIG fish.', Cost: '4 gp' },
  },
  {
    name: 'Quiver & Ammo',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: "Don't leave home without it. Cost: 10 gp.",
    stats: { Properties: "Don't leave home without it.", Cost: '10 gp' },
  },
  {
    name: 'Saw',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'For cutting lumber. Cost: 4 gp.',
    stats: { Properties: 'For cutting lumber.', Cost: '4 gp' },
  },
  {
    name: 'Soap',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Useless. Cost: 1 sp.',
    stats: { Properties: 'Useless.', Cost: '1 sp' },
  },
  {
    name: 'Strange Plant',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Who knows? Cost: 5 sp.',
    stats: { Properties: 'Who knows?', Cost: '5 sp' },
  },
  {
    name: 'Shiny Object',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Worthless, but VERY pretty. Cost: 1 sp.',
    stats: { Properties: 'Worthless, but VERY pretty.', Cost: '1 sp' },
  },
  {
    name: 'Lock Pick',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: "It's not mine, honest! Cost: 5 gp.",
    stats: { Properties: "It's not mine, honest!", Cost: '5 gp' },
  },
  {
    name: 'Bell',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'For service. Cost: 2 gp.',
    stats: { Properties: 'For service.', Cost: '2 gp' },
  },
  {
    name: 'Dice',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'LOTS of fun. Cost: 5 sp.',
    stats: { Properties: 'LOTS of fun.', Cost: '5 sp' },
  },
  {
    name: 'Blanket',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Warm & fuzzy. Cost: 1 gp.',
    stats: { Properties: 'Warm & fuzzy.', Cost: '1 gp' },
  },
  {
    name: 'Hunting Trap',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: "Snap snap, don't lose a finger! Cost: 10 gp.",
    stats: { Properties: "Snap snap, don't lose a finger!", Cost: '10 gp' },
  },
  {
    name: 'Camping Supplies',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Bedroll, rations, simple tent. Cost: 5 gp.',
    stats: { Properties: 'Bedroll, rations, simple tent.', Cost: '5 gp' },
  },
  {
    name: 'Crowbar',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: "It's LIKE a key. Cost: 2 gp.",
    stats: { Properties: "It's LIKE a key.", Cost: '2 gp' },
  },
  {
    name: 'Pitons',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Metal spikes, for sealing doors. Cost: 5 gp.',
    stats: { Properties: 'Metal spikes, for sealing doors.', Cost: '5 gp' },
  },
  {
    name: 'Manacles',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'For when someone has been bad. Cost: 3 gp.',
    stats: { Properties: 'For when someone has been bad.', Cost: '3 gp' },
  },
  {
    name: 'Large Sack',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Like a BIG pocket. Cost: 5 sp.',
    stats: { Properties: 'Like a BIG pocket.', Cost: '5 sp' },
  },
  {
    name: 'Instrument',
    item_type: 'Adventuring Gear',
    rarity: 'Common',
    tags: ['Adventuring Gear'],
    description: 'Drums, Horn, Lyre, Flute, etc. Cost: 5-50 gp.',
    stats: { Properties: 'Drums, Horn, Lyre, Flute, etc.', Cost: '5-50 gp' },
  },
  // --- Magical Items ---
  {
    name: 'Weapon of Many Hands',
    item_type: 'Magic Item',
    rarity: 'Varies',
    tags: ['Magic Item', 'Weapon'],
    description:
      'While equipped, this weapon grants the wearer additional arms. The wearer can use the extra arms to perform any task their normal hands can do (wield equipment, Grapple enemies, climb, etc.) but does not allow the wearer to perform actions any faster. These extra appendages may be horrifying to people in polite society. A weapon that grants 1 extra hand is likely to be Uncommon; 4 extra hands, Legendary.',
    stats: { Effect: 'Grants additional functional arms while equipped.', Rarity: 'Uncommon (1 hand) to Legendary (4 hands)' },
  },
  {
    name: 'Weapon of Animosity',
    item_type: 'Magic Item',
    rarity: 'Varies',
    tags: ['Magic Item', 'Weapon'],
    description:
      'Whenever you attack with this weapon, roll an additional animosity die. The weapon deals that much additional damage to your target on a hit. Whenever this weapon misses, you take that damage instead. A weapon that adds 1d4 is likely to be Uncommon; 1d10 or greater, Legendary.',
    stats: { Effect: 'Extra damage die on hit; wielder takes that damage on a miss.', Rarity: 'Uncommon (1d4) to Legendary (1d10+)' },
  },
  {
    name: 'Weapon of Slaying',
    item_type: 'Magic Item',
    rarity: 'Varies',
    tags: ['Magic Item', 'Weapon'],
    description:
      'Whenever you attack with this weapon, it deals an additional die of damage against a particular creature type. Those creatures may try to kill you first. A 1d4 weapon of slaying is likely to be Uncommon; +1d10 or more, Legendary.',
    stats: { Effect: 'Extra damage die vs. a chosen creature type.', Rarity: 'Uncommon (1d4) to Legendary (1d10+)' },
  },
  {
    name: 'Gnatbane Weapon',
    item_type: 'Magic Item',
    rarity: 'Uncommon',
    tags: ['Magic Item', 'Weapon'],
    description: 'Does not miss Small or Tiny creatures (they may hate you for it and attack you first).',
    stats: { Effect: 'Never misses Small or Tiny creatures.' },
  },
  {
    name: "Harbinger & Sovereign, Abyssal's Claim",
    item_type: 'Magic Item',
    rarity: 'Legendary',
    tags: ['Magic Item', 'Weapon', 'Named Item'],
    description:
      'A set of 2 matching legendary glaives. Grants +4 extra arms while both are equipped (see Weapon of Many Hands).',
    stats: { Effect: '+4 extra arms while both glaives are equipped.' },
  },
  {
    name: 'Weapon of Wounding',
    item_type: 'Magic Item',
    rarity: 'Uncommon',
    tags: ['Magic Item', 'Weapon'],
    description: 'When you land a hit with this weapon, you may suffer 1d6 damage to deal twice that much additional damage to your target.',
    stats: { Effect: 'Suffer 1d6 damage to deal double that as bonus damage on hit.' },
  },
  {
    name: 'Handwraps of Force',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item', 'Wearable'],
    description:
      'While wearing these wraps, whenever you make an unarmed strike, you may push your target up to 2 spaces and yourself the same distance in the opposite direction. You may instead make an attack with no target, striking the air to propel yourself 4 spaces in any direction.',
    stats: { Effect: 'Push on unarmed strike hit, or self-propel 4 spaces with a targetless attack.' },
  },
  {
    name: "Vindication",
    item_type: 'Magic Item',
    rarity: 'Legendary',
    tags: ['Magic Item', 'Weapon', 'Named Item'],
    description:
      'A jagged blade marred by scorch marks and dark stains, radiating a bitter, vengeful energy that punishes both wielder and foe alike. A Legendary Weapon of Animosity: deals +1d12 damage on hit; you take that damage on a miss.',
    stats: { Effect: 'Weapon of Animosity (+1d12 damage on hit / self-damage on miss).' },
  },
  {
    name: 'Trinket of Ill Omen',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item', 'Wearable'],
    description: 'While equipped, you have -1 to saves you roll and +1 to your save DC.',
    stats: { Effect: '-1 to your saves, +1 to your save DC, while equipped.' },
  },
  {
    name: 'Pocket Cauldron',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item'],
    description:
      "While Safe Resting, use this to brew your choice of 1 potion, to be consumed immediately: Elixir of Futuresight (a brief, cryptic vision of a future event), Elixir of Requiem (relive a crucial memory from the drinker's past), or Elixir of Time (once every 100 years, the cauldron can brew a potion that takes the drinker back in time 1 day).",
    stats: { Effect: 'During a Safe Rest, brew one of: Elixir of Futuresight, Elixir of Requiem, or Elixir of Time.' },
  },
  {
    name: 'Mindlink Daggers',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item', 'Weapon', 'Named Item'],
    description:
      'A matched pair of slender, silver daggers with intertwining runes. Enables the sharing of thoughts between any who holds (or is stabbed by) one.',
    stats: { Effect: 'Shares thoughts telepathically between holders (or those stabbed by the daggers).' },
  },
  {
    name: 'Skitter Shoes',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item', 'Wearable'],
    description:
      'While wearing these shoes, you can walk on vertical surfaces or ceilings as if they were flat ground, but only at half your normal Speed. If you end your turn upside down or on a vertical surface, you must make a DC 10 STR save or fall down, landing prone.',
    stats: { Effect: 'Walk on walls/ceilings at half Speed; DC 10 STR save or fall prone if you end your turn there.' },
  },
  {
    name: 'Bloodstained Quill',
    item_type: 'Magic Item',
    rarity: 'Uncommon',
    tags: ['Magic Item'],
    description:
      'If you dip this quill into the blood of a dead intelligent creature, the quill animates and writes the last words spoken by that creature.',
    stats: { Effect: 'Dipped in the blood of a dead intelligent creature, writes their last words.' },
  },
  {
    name: 'Resolute Fangs, Golden Bastion',
    item_type: 'Magic Item',
    rarity: 'Legendary',
    tags: ['Magic Item', 'Shield', 'Named Item'],
    description:
      "A legendary shield granting +8 Armor. Reaction: when you reduce damage from a melee attack with this shield, you may Grapple the attacker regardless of its size (escape DC 20 STR, max 1 creature). Action: speak this shield's command word to make it immovable, fixed in place, until it is spoken again.",
    stats: { Armor: '8', Effect: 'Reaction: Grapple a melee attacker (escape DC 20 STR). Action: speak command word to fix it immovably in place.' },
  },
  {
    name: 'Key of Doors',
    item_type: 'Magic Item',
    rarity: 'Very Rare',
    tags: ['Magic Item', 'Named Item'],
    description: "Insert this key into any locked door to open it, not to the room beyond, but to any doorway you've previously walked through while holding this item.",
    stats: { Effect: 'Opens any locked door into any doorway you have previously walked through while holding the key.' },
  },
  {
    name: 'Eyes of the Street',
    item_type: 'Magic Item',
    rarity: 'Uncommon',
    tags: ['Magic Item', 'Wearable'],
    description:
      "A pair of goggles covered in muck that you can't ever clean off completely. While wearing them, you can look at a rat or a pigeon to gain the ability to see and hear through its senses for 10 minutes. Once you use this ability, you must whisper a secret to the goggles before you can use them again. That secret always seems to become a local rumor before too long.",
    stats: { Effect: 'Once used, see/hear through a rat or pigeon for 10 minutes. Recharges by whispering a secret to the goggles.' },
  },
  {
    name: 'Grim Coronet',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item', 'Wearable', 'Named Item'],
    description: 'When you would die while wearing this crown, gain 3 actions and take a turn immediately. You die at the end of that turn.',
    stats: { Effect: 'On death, gain a final turn with 3 actions, then die at its end.' },
  },
  {
    name: 'Ball of Spiders',
    item_type: 'Magic Item',
    rarity: 'Uncommon',
    tags: ['Magic Item'],
    description:
      'A black, palm-sized ball with faintly writhing patterns etched into its surface. Action: Throw this ball up to 6 spaces. Upon impact, it shatters, releasing a swarm of harmless but horrifyingly realistic spectral spiders that cover a 2x2 area. Creatures in the area must make a WIL save or be Frightened until the end of their next turn. Once used, the ball reforms at the next Safe Rest.',
    stats: { Effect: 'Action: throw up to 6 spaces; 2x2 spectral spider burst, WIL save or Frightened.', Recharge: 'Reforms at the next Safe Rest.' },
  },
  {
    name: 'Phoenix Helm',
    item_type: 'Magic Item',
    rarity: 'Legendary',
    tags: ['Magic Item', 'Wearable', 'Named Item'],
    description:
      "If you die while wearing this golden helm, your body explodes in flames and hot ash. You rise anew from the ashes (see the GM's Guide for full resurrection details).",
    stats: { Effect: 'On death while worn, explode into flame and ash and rise anew from the ashes.' },
  },
  {
    name: 'Button of Protection',
    item_type: 'Magic Item',
    rarity: 'Rare',
    tags: ['Magic Item', 'Wearable'],
    description:
      'A small, unassuming button etched with a faintly glowing sigil. When sewn onto an outfit, as a reaction when you are attacked, you may pull the button off and throw it into the air. The button emits a sudden, dazzling flash of light and a high-pitched whistle: the attacker must make a WIL save or be distracted, causing the attack to miss you. After use, the button becomes inert. It can be sewn back onto a garment during a Safe Rest by an experienced seamstress or tailor with silver thread, which reactivates its power.',
    stats: { Effect: 'Reaction when attacked: attacker makes a WIL save or the attack automatically misses.', Recharge: "Re-sewn with silver thread by an experienced seamstress/tailor during a Safe Rest." },
  },
  // --- Spell Scrolls & Wands: named wands ---
  {
    name: 'Wand of Firestep',
    item_type: 'Wand',
    rarity: 'Uncommon',
    tags: ['Wand', 'Magic Item'],
    description:
      'An Uncommon wand that casts a Cantrip-tier spell without expending mana or requiring magical ability. Has 3 charges.',
    stats: { Tier: 'Cantrip', Charges: '3', Recharge: "Heat the wand in a blacksmith's forge until it glows, then quench it in oil." },
  },
  {
    name: 'Wand of Barrier of Wind',
    item_type: 'Wand',
    rarity: 'Rare',
    tags: ['Wand', 'Magic Item'],
    description: 'A Rare wand that casts a Tier 2 spell without expending mana or requiring magical ability. Has 3 charges.',
    stats: { Tier: 'Tier 2', Charges: '3', Recharge: 'Hang the wand with wind chimes in a breezy area. Let it ring for 3 days.' },
  },
  {
    name: 'Wand of Dread Visage',
    item_type: 'Wand',
    rarity: 'Uncommon',
    tags: ['Wand', 'Magic Item'],
    description: 'An Uncommon wand that casts a Tier 2 spell without expending mana or requiring magical ability. Has 2 charges.',
    stats: { Tier: 'Tier 2', Charges: '2', Recharge: 'Place the wand in a freshly slain corpse. Leave it until only bones remain.' },
  },
  {
    name: 'Wand of Sacrifice',
    item_type: 'Wand',
    rarity: 'Very Rare',
    tags: ['Wand', 'Magic Item'],
    description: 'A Very Rare wand that casts a Tier 6 spell without expending mana or requiring magical ability. Has 1 charge.',
    stats: { Tier: 'Tier 6', Charges: '1', Recharge: 'Plant it in a new garden, leave it undisturbed until the flowers bloom.' },
  },
  {
    name: 'Wand of Fly',
    item_type: 'Wand',
    rarity: 'Uncommon',
    tags: ['Wand', 'Magic Item'],
    description: 'An Uncommon wand that casts a Tier 3 spell without expending mana or requiring magical ability. Has 2 charges.',
    stats: { Tier: 'Tier 3', Charges: '2', Recharge: 'Give it to a wild bird and let it fly freely. Retrieve it wherever the bird drops it.' },
  },
  {
    name: "Elderwyrm's Majesty",
    item_type: 'Wand',
    rarity: 'Legendary',
    tags: ['Wand', 'Magic Item', 'Named Item'],
    description:
      'A Legendary Tier 9 wand with 1 charge. This wand can cast Dragonform, turning into the type of dragon that last charged it.',
    stats: { Tier: 'Tier 9', Charges: '1', Recharge: 'Give an ancient dragon a gift it truly desires.', Effect: 'Casts Dragonform, becoming the dragon type that last recharged it.' },
  },
  {
    name: 'Wand of Glacier Strike',
    item_type: 'Wand',
    rarity: 'Very Rare',
    tags: ['Wand', 'Magic Item'],
    description: 'A Very Rare wand that casts a Tier 8 spell without expending mana or requiring magical ability. Has 1 charge.',
    stats: { Tier: 'Tier 8', Charges: '1', Recharge: 'Leave the wand at the bottom of a lake until it freezes over and thaws naturally.' },
  },
  {
    name: 'Wand of Ride the Lightning',
    item_type: 'Wand',
    rarity: 'Very Rare',
    tags: ['Wand', 'Magic Item'],
    description: 'A Very Rare wand that casts a Tier 6 spell without expending mana or requiring magical ability. Has 2 charges.',
    stats: { Tier: 'Tier 6', Charges: '2', Recharge: 'Place at the highest point within 1 mile. Retrieve after 3 thunderstorms.' },
  },
  {
    name: 'Heartwood, Splinter of the Tree of Life',
    item_type: 'Wand',
    rarity: 'Legendary',
    tags: ['Wand', 'Magic Item', 'Named Item'],
    description: 'A Legendary Tier 9 wand with 1 charge. Casts Redeem with no required components.',
    stats: { Tier: 'Tier 9', Charges: '1', Recharge: 'A sacred hymn must be sung over it ceaselessly for 100 years.', Effect: 'Casts Redeem with no required components.' },
  },
];

const FEY_LOOT_ITEMS: RawItem[] = [
  {
    name: 'Fey Prank Kit',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Fey Loot'],
    description:
      'A grab bag of the mundane novelties found on defeated Fey: sneezing powder, stink bombs, cayenne pepper, whoopie cushions, scrolls containing jokes or poetry, a double-headed coin, tiny and ornate weapons, and tiny crowns set with gems. Mostly flavorful clutter, but a curious GM could easily rule the sneezing powder or stink bombs usable as an improvised distraction or nonlethal deterrent.',
    stats: {},
  },
  {
    name: 'Headband of Rapid Hair Growth',
    item_type: 'Magic Item',
    rarity: 'Uncommon (cursed)',
    tags: ['Loot', 'Fey Loot', 'Magic Item', 'Cursed'],
    description:
      "One of the Fey's slightly-cursed magical items. Named but left undetailed in the source text; a Fey-flavored curse item implied to make the wearer's hair grow at an alarming, comedic rate. Left to the GM to adjudicate specific mechanics.",
    stats: {},
  },
  {
    name: 'Bell of Constant Ringing',
    item_type: 'Magic Item',
    rarity: 'Uncommon (cursed)',
    tags: ['Loot', 'Fey Loot', 'Magic Item', 'Cursed'],
    description:
      "One of the Fey's slightly-cursed magical items. Named but left undetailed in the source text; implied to ring incessantly once acquired, making stealth difficult for its bearer. Left to the GM to adjudicate specific mechanics.",
    stats: {},
  },
  {
    name: 'Gloves of Gesticulation',
    item_type: 'Magic Item',
    rarity: 'Uncommon (cursed)',
    tags: ['Loot', 'Fey Loot', 'Magic Item', 'Cursed'],
    description:
      "One of the Fey's slightly-cursed magical items. Named but left undetailed in the source text; implied to cause the wearer's hands to gesture wildly and uncontrollably. Left to the GM to adjudicate specific mechanics.",
    stats: {},
  },
];

const BUG_LOOT_ITEMS: RawItem[] = [
  // Swarming Bugs loot
  {
    name: 'Pheromone Sac',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: 'Single use. Action: control all Bug Minions within Reach 2 for 1 round.',
    stats: { Uses: 'Single use', Effect: 'Action: control all Bug Minions within Reach 2 for 1 round.' },
  },
  {
    name: 'Bonfire Bug Organ',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: "Action: throw up to 2+STR spaces. Deals 1d20 damage to all adjacent spaces where it impacts.",
    stats: { Effect: 'Action: throw up to 2+STR spaces; 1d20 damage to all adjacent spaces on impact.' },
  },
  {
    name: 'Iridescent Bug Wings',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot', 'Trade Good'],
    description: 'Beautiful. Valuable to clothiers, nobility, as well as less-civilized creatures.',
    stats: {},
  },
  {
    name: 'Hooked Articulating Leg',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: 'Can be used to grab small objects within Reach 2.',
    stats: { Effect: 'Grab small objects within Reach 2.' },
  },
  {
    name: 'Bug Larva',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: '1d4 portions. Consume a portion (if you can stomach it) during a Rest to regain 1 HD.',
    stats: { Portions: '1d4', Effect: 'Consume during a Rest to regain 1 HD.' },
  },
  {
    name: 'Jacker Toxin',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: 'When ingested or injected, a creature will see you as an ally for a brief time.',
    stats: { Effect: 'Ingested/injected: target treats you as an ally for a brief time.' },
  },
  // Mighty Bugs loot
  {
    name: 'Chitinous Plate',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot', 'Shield'],
    description: 'Acts as a Shield: +10 Armor. Brittle (irreparably destroyed when crit).',
    stats: { Armor: '10', Properties: 'Brittle (irreparably destroyed when crit).' },
  },
  {
    name: 'Mighty Horn',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot', 'Weapon'],
    description: 'A weapon. Damage: 1d10+STR Piercing. Properties: Reach 2, Light, 1-handed, Brittle (irreparably destroyed on crit).',
    stats: { Damage: '1d10+STR Piercing', Properties: 'Reach 2, Light, 1-handed, Brittle (irreparably destroyed on crit)' },
  },
  {
    name: 'Bugmeat',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: '1d4 portions. Action: consume a portion to gain 10 temp HP and advantage on STR saves while the temp HP lasts.',
    stats: { Portions: '1d4', Effect: 'Action: consume for 10 temp HP + advantage on STR saves while it lasts.' },
  },
  {
    name: 'Bug Spit',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: '1d4 portions. Acts as a powerful glue.',
    stats: { Portions: '1d4', Effect: 'Acts as a powerful glue.' },
  },
  {
    name: 'Broodfly Claw',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot', 'Weapon'],
    description: 'A weapon. Damage: 2d4+DEX Slashing. Properties: Vicious 2, Brittle (irreparably destroyed on crit).',
    stats: { Damage: '2d4+DEX Slashing', Properties: 'Vicious 2, Brittle (irreparably destroyed on crit)' },
  },
  {
    name: 'Intact Resonance Chamber',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot', 'Trade Good'],
    description: 'Multiplies sounds many times over. Very valuable to researchers.',
    stats: {},
  },
  {
    name: 'Stalker Grease',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: '1d4 portions. Use a portion to gain +10 to Stealth checks for 1 hour.',
    stats: { Portions: '1d4', Effect: '+10 to Stealth checks for 1 hour.' },
  },
  {
    name: 'Bottled Fumes',
    item_type: 'Loot',
    rarity: 'Common',
    tags: ['Loot', 'Bug Loot'],
    description: 'Action: throw up to STR+2 spaces. Creatures in a 2x2 area are Poisoned for 1 round.',
    stats: { Effect: 'Action: throw up to STR+2 spaces; 2x2 area Poisoned for 1 round.' },
  },
];

async function main() {
  const client = createSupabaseClient();

  const items: ItemInput[] = [
    ...CORE_RULES_ITEMS.map(coreItem),
    ...FEY_LOOT_ITEMS.map(feyItem),
    ...BUG_LOOT_ITEMS.map(bugItem),
  ];

  let created = 0;
  for (const item of items) {
    await createItem(client, item);
    created += 1;
  }

  console.log(`Seeded ${created} Nimble items (Core Rules: ${CORE_RULES_ITEMS.length}, Fey Loot: ${FEY_LOOT_ITEMS.length}, Bug Loot: ${BUG_LOOT_ITEMS.length}).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
